version: '3.8'
services:
  reactapp:
    build: .
    container_name: falabella
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    volumes:
      - .:/app
      - /app/node_modules
      

